openapi: 3.0.0
info:
  title: My API
  version: '1.0'
paths:
  /greeting:
    post:
      summary: Post a greeting
      operationId: app.post_greeting
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                greeting:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
