openapi: 3.0.0
info:
  title: My API
  version: '1.0'
paths:
  /greeting:
    post:
      summary: Post a greeting
      operationId: app.post_greeting
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                greeting:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string

  /users:
    get:
      summary: Retrieve list of users
      operationId: controllers.user_controller.get_users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: string
