"""Add status for user

Revision ID: 6d2b45de6405
Revises: 20c0aae27013
Create Date: 2024-09-13 17:19:49.709847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d2b45de6405'
down_revision: Union[str, None] = '20c0aae27013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = sa.Enum('CREATING', 'READY', 'DELETED', name='status_enum')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('user', sa.Column('status', status_enum, nullable=True))
    op.execute(
        "UPDATE public.user SET status = 'CREATING' WHERE status IS NULL"
    )
    op.alter_column('user', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    # ### end Alembic commands ###
