"""Add phone for user

Revision ID: 901fdf910d4d
Revises: 6d2b45de6405
Create Date: 2024-09-18 20:43:09.772885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '901fdf910d4d'
down_revision: Union[str, None] = '6d2b45de6405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(), nullable=True))
    op.execute(
        "UPDATE public.user SET phone = 'UNKNOWNED' WHERE phone IS NULL"
    )
    op.alter_column('user', 'phone', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
