name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installe les dépendances du projet
        pip install flake8 pytest  # Installe flake8 et pytest

    - name: Run tests
      run: |
        make test

    - name: Lint with flake8
      run: |
        make flake

    - name: Isort
      run: |
        make isort-check

    - name: SonarCloud Scan
      uses: sonarsource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        sonarHostUrl: "https://sonarcloud.io"
        organization: "AurelieVidal"
        projectKey: "aurelievidal"