name: CI Pipeline

# Déclenchement de la CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Jobs définis dans le pipeline
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Vérifier le code du repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Installer Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"  # Remplace avec ta version de Python si nécessaire

    # 3. Installer les dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installe les dépendances du projet
        pip install flake8 pytest  # Installe flake8 et pytest

    # 4. Lancer les tests unitaires
    - name: Run tests
      run: |
        make test

    # 5. Vérifier la qualité du code avec Flake8
    - name: Lint with flake8
      run: |
        make flake

    - name: Isort
      run: |
        make isort-check

    - name: Mypy
      run: |
        make mypy

    - name: Bandit
      run: |
        make bandit

    - name: Safety
      run: |
        make safety