name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        make test

    - name: Run mutmut
      run: |
        make mutmut
        if make mutmut_results | grep -q '^survived'; then
          echo "❌ Des mutants ont survécu! Renforcez vos tests."
          exit 1
        fi

    - name: Lint with flake8
      run: |
        make flake

    - name: Isort
      run: |
        make isort-check

    - name: Pylint
      run: |
        make pylint
